
import "./globals.css"
import { UserProvider } from '@auth0/nextjs-auth0/client';
import { i18n } from "@/../i18n.config";
import { Poppins } from "next/font/google"
import Header from "@/components/header";
import Footerlang from "@/components/Footerlang";
import { PostsProvider } from "./PostsProvider";
import { FeedbacksProvider } from "./FeedbacksProvider";
import { CommentsProvider } from "./CommentsProvider ";
import { Fab } from "@/components";

const poppins = Poppins({ weight: '400', subsets: ['latin'] })

export const metadata = {
  title: "International Neurologic Diseases Association",
  description: "Generated by LAEDX"
}


export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

export default function RootLayout({ children, params }) {
  return (

    <html lang={params.lang}>
      <UserProvider>
        <body className={poppins.className}>
          <Header lang={params.lang} />
          <Fab />
          <PostsProvider>
            <CommentsProvider>
              <FeedbacksProvider>
                <main>{children}</main>
              </FeedbacksProvider>
            </CommentsProvider>
          </PostsProvider>
          <Footerlang lang={params.lang} />
        </body>

      </UserProvider>
    </html>

  )
}
